import os
import json
import re
import io
import zipfile
from datetime import datetime
from flask import Flask, render_template, request, flash, redirect, url_for, send_file

app = Flask(__name__)
app.secret_key = 'supersecretkey'

# --- Configuration ---
# --- Configuration ---
if os.path.exists("/config"):
    CONFIG_FILE = "/config/settings.json"
    BASE_DIR = "/data"
else:
    # Fallback for local testing
    CONFIG_FILE = os.path.join(os.getcwd(), "config", "settings.json")
    BASE_DIR = os.path.join(os.getcwd(), "data")

# Default structure
DEFAULT_DATA = {
    "clients": [],
    "presets": {
        "Standard Design": [
            "01_Admin/Brief", "01_Admin/Quote", "01_Admin/Supplied-Files", "01_Admin/Approvals", "01_Admin/Client-Feedback",
            "02_Assets/Links", "02_Assets/Fonts",
            "03_Design/01_Discover/Workshop", "03_Design/01_Discover/Playback",
            "03_Design/02_Concepts",
            "03_Design/03_Design-Dev/Touchpoint", "03_Design/03_Design-Dev/Figma-Backup",
            "03_Design/04_Artwork"
        ],
        "Motion Design": [
            "01_Admin/Brief", "01_Admin/Quote", "01_Admin/Supplied-Files", "01_Admin/Approvals", "01_Admin/Client-Feedback",
            "02_Assets/Links", "02_Assets/Fonts",
            "03_Design/01_Discover/Workshop", "03_Design/01_Discover/Playback",
            "03_Design/02_Concepts",
            "03_Design/03_Design-Dev/Touchpoint", "03_Design/03_Design-Dev/Figma-Backup",
            "03_Design/04_Artwork",
            "05_Motion/01_Storyboard", "05_Motion/02_Edit", "05_Motion/03_Animation", "05_Motion/04_Audio", "05_Motion/05_Renders"
        ],
        "Simple Design": [
            "01_Admin/Brief", "01_Admin/Supplied-Files", "01_Admin/Approvals", "01_Admin/Client-Feedback",
            "02_Assets/Links", "02_Assets/Fonts",
            "03_Design/01_Concepts", "03_Design/02_Final"
        ]
    }
}

def load_data():
    if not os.path.exists(CONFIG_FILE):
        # Ensure directory exists before writing
        os.makedirs(os.path.dirname(CONFIG_FILE), exist_ok=True)
        save_data(DEFAULT_DATA)
        return DEFAULT_DATA
    with open(CONFIG_FILE, 'r') as f:
        return json.load(f)

def save_data(data):
    os.makedirs(os.path.dirname(CONFIG_FILE), exist_ok=True)
    with open(CONFIG_FILE, 'w') as f:
        json.dump(data, f, indent=4)

def slugify(text, lower=True):
    if lower:
        text = text.lower()
    text = re.sub(r'[\s_]+', '-', text)
    return re.sub(r'[^a-zA-Z0-9\-]', '', text)

def get_readme_content(preset_name, project_name, client_name, client_code, job_no, date_str):
    # Common Sections
    header = f"""# {project_name}

## Project Details

- **Client:** {client_name} ({client_code})
- **Project Name:** {project_name}
- **Job Number:** {job_no}
- **Created:** {datetime.now().strftime("%d %B %Y")}

## Naming Conventions

This project follows standardised naming conventions:

- All folder and file names use **underscores** (`_`) instead of spaces
- Folders are numbered sequentially for organisation (e.g., `01_Admin`, `02_Assets`)
- Maintain consistency throughout the project lifecycle
"""

    footer = """
## How to Use This Structure

1. **Organise Files:** Place files in their appropriate folders based on project phase and file type
2. **Maintain Structure:** Keep the folder structure intact throughout the project
3. **Version Control:** Consider adding version numbers or dates to file names when saving iterations
4. **Archive:** At project completion, ensure all files are in their correct locations for archival

## Best Practices

- Keep folder names consistent with this structure
- Use descriptive file names that indicate content and version
- Archive old versions in a separate `_Archive` subfolder if needed
- Document major decisions in the relevant Admin subfolders
- Regularly back up your work

---

*This folder structure was generated by Project Folder Generator*
"""

    # Preset Specifics
    structure = ""
    purposes = ""

    if preset_name == "Standard Design":
        structure = """## Folder Structure

```
├── 01_Admin - Administrative and project management files
│   ├── Brief - Project brief and requirements documentation
│   ├── Quote
│   ├── Supplied-Files
│   ├── Approvals
│   └── Client-Feedback
├── 02_Assets - Project assets and resources
│   ├── Links - Images, illustrations, logos, and all visual assets required by the project
│   └── Fonts - Typography files and font resources
└── 03_Design - Design files and creative work
    ├── 01_Discover
    │   ├── Workshop
    │   └── Playback
    ├── 02_Concepts
    ├── 03_Design-Dev
    │   ├── Touchpoint
    │   └── Figma-Backup
    └── 04_Artwork
```"""
        purposes = """## Folder Purposes

### 01_Admin
Administrative and project management files. Contains Briefs, Quotes, Approvals, etc.

### 02_Assets
Project assets and resources including Links (images/logos) and Fonts.

### 03_Design
Design files and creative work split into phases:
- **01_Discover**: Workshops and Playbacks
- **02_Concepts**: Initial design concepts
- **03_Design-Dev**: Touchpoints and Backups
- **04_Artwork**: Final production artwork
"""

    elif preset_name == "Motion Design":
        structure = """## Folder Structure

```
├── 01_Admin
│   ├── Brief
│   ├── Quote
│   ├── Supplied-Files
│   ├── Approvals
│   └── Client-Feedback
├── 02_Assets
│   ├── Links
│   └── Fonts
├── 03_Design
│   ├── 01_Discover
│   ├── 02_Concepts
│   ├── 03_Design-Dev
│   └── 04_Artwork
└── 05_Motion - Motion graphics specific files
    ├── 01_Storyboard
    ├── 02_Edit
    ├── 03_Animation
    ├── 04_Audio
    └── 05_Renders
```"""
        purposes = """## Folder Purposes

### 01_Admin & 02_Assets
Standard administrative and asset folders.

### 03_Design
Static design assets and source files.

### 05_Motion
Dedicated motion graphics workflow:
- **01_Storyboard**: Visual planning and boards
- **02_Edit**: Video editing project files
- **03_Animation**: After Effects / Animation project files
- **04_Audio**: Sound effects, music, and voiceovers
- **05_Renders**: Final video exports and WIP renders
"""

    elif preset_name == "Simple Design":
        structure = """## Folder Structure

```
├── 01_Admin
│   ├── Brief
│   ├── Supplied-Files
│   ├── Approvals
│   └── Client-Feedback
├── 02_Assets
│   ├── Links
│   └── Fonts
└── 03_Design
    ├── 01_Concepts
    └── 02_Final
```"""
        purposes = """## Folder Purposes

### 01_Admin
Simplified admin documentation (Briefs, Approvals).

### 02_Assets
Images, logos, and fonts.

### 03_Design
Streamlined design workflow:
- **01_Concepts**: Working files and iterations
- **02_Final**: Finalised designs ready for delivery
"""

    return f"{header}\n{structure}\n\n{purposes}\n{footer}"

@app.route('/', methods=['GET', 'POST'])
def index():
    data = load_data()
    
    if request.method == 'POST':
        action = request.form.get('action') # 'create' or 'download'
        job_no = request.form.get('job_no', '').strip()
        client_index = request.form.get('client_index')
        project_name = request.form.get('project_name', '').strip()
        preset_name = request.form.get('preset')

        if not all([job_no, client_index, project_name, preset_name]):
            flash("Error: All fields are required.", "error")
            return render_template('index.html', data=data)

        # Get client details
        client = data['clients'][int(client_index)]
        client_code = client['code']

        # Generate Name
        # Generate Name
        date_str = datetime.now().strftime("%Y-%m")
        
        # Project Name: Sentence case (Capitalize first letter, lower rest of words, hyphens for spaces)
        # e.g. "summer campaign" -> "Summer-campaign"
        safe_project_name = slugify(project_name.capitalize(), lower=False)
        
        safe_job_no = slugify(job_no)
        
        # Client Code: Uppercase
        safe_client_code = slugify(client_code, lower=False).upper()
        
        append_date = request.form.get('append_date')
        
        if append_date:
            folder_name = f"{safe_job_no}_{safe_client_code}_{safe_project_name}_{date_str}"
        else:
            folder_name = f"{safe_job_no}_{safe_client_code}_{safe_project_name}"
        
        # Get list of subfolders
        subfolders = data['presets'][preset_name]

        # --- OPTION A: DOWNLOAD ZIP ---
        if action == 'download':
            memory_file = io.BytesIO()
            with zipfile.ZipFile(memory_file, 'w', zipfile.ZIP_DEFLATED) as zf:
                zf.writestr(f"{folder_name}/", "")
                # Add README
                readme_content = get_readme_content(preset_name, project_name, client['name'], client_code, job_no, date_str)
                zf.writestr(f"{folder_name}/README.md", readme_content)

                for path in subfolders:
                    clean_path = path.strip('/')
                    # Ensure we use forward slashes for zip compatibility
                    full_zip_path = f"{folder_name}/{clean_path}/"
                    zf.writestr(full_zip_path, "")
            
            memory_file.seek(0)
            return send_file(
                memory_file, 
                download_name=f"{folder_name}.zip", 
                as_attachment=True
            )

        # --- OPTION B: CREATE ON NAS ---
        elif action == 'create':
            full_path = os.path.join(BASE_DIR, folder_name)

            if os.path.exists(full_path):
                flash(f"Error: Folder '{folder_name}' already exists on NAS!", "error")
            else:
                try:
                    os.makedirs(full_path, exist_ok=True)
                    
                    # Create README
                    readme_content = get_readme_content(preset_name, project_name, client['name'], client_code, job_no, date_str)
                    with open(os.path.join(full_path, "README.md"), "w") as f:
                        f.write(readme_content)

                    for path in subfolders:
                        sub_path = os.path.join(full_path, path.strip('/'))
                        os.makedirs(sub_path, exist_ok=True)
                    
                    flash(f"Success! Created '{folder_name}' on NAS.", "success")
                except Exception as e:
                    flash(f"Error creating folders: {str(e)}", "error")

    return render_template('index.html', data=data)

@app.route('/settings', methods=['GET', 'POST'])
def settings():
    data = load_data()
    
    if request.method == 'POST':
        action = request.form.get('action')
        
        if action == 'add_client':
            name = request.form.get('client_name')
            code = request.form.get('client_code')
            if name and code:
                code = code.upper() # Force uppercase
                data['clients'].append({'name': name, 'code': code})
                save_data(data)
                flash(f"Added client {name}", "success")

        elif action == 'delete_client':
            index = int(request.form.get('client_index'))
            del data['clients'][index]
            save_data(data)
            flash("Client deleted", "success")

        elif action == 'add_preset':
            p_name = request.form.get('preset_name')
            p_content = request.form.get('preset_content').splitlines()
            p_content = [x.strip() for x in p_content if x.strip()]
            
            if p_name and p_content:
                data['presets'][p_name] = p_content
                save_data(data)
            if p_name and p_content:
                data['presets'][p_name] = p_content
                save_data(data)
                flash(f"Preset '{p_name}' saved", "success")

        elif action == 'edit_preset':
            # Same as add, just conceptually different but uses overwrite logic of dict
            p_name = request.form.get('preset_name')
            p_content = request.form.get('preset_content').splitlines()
            p_content = [x.strip() for x in p_content if x.strip()]
            
            if p_name and p_content:
                data['presets'][p_name] = p_content
                save_data(data)
                flash(f"Preset '{p_name}' updated", "success")

        elif action == 'delete_preset':
            p_name = request.form.get('preset_name')
            if p_name in data['presets']:
                del data['presets'][p_name]
                save_data(data)
                flash(f"Deleted preset {p_name}", "success")

        return redirect(url_for('settings'))

    return render_template('settings.html', data=data)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
